#pragma once
#include "Core.h"
#include "Log.h"
#include "Animation.h"

/*
* A structure representing a bitmap font.
*/
typedef struct BitmapFont 
{
	bool invertY;
	vec2 CellFactors;
	float advanceFactor;
	uint32_t rowPitch;
	char baseCharOffset;
	char charWidths[256];
	GLTexture* FontTexture;
} BitmapFont;

/*
* Load a bitmap font from disk. Accepts .bff files generated by CodeHead's bitmap font generator.
*/
BitmapFont* LoadBitmapFont(const char* filepath, bool invertY);
/*
* Release the resources owned by a bitmap font.
*/
void DeleteBitmapFont(BitmapFont* font);

/*
* Get the parameters of a character in a bitmap font given the font size.
* Returns the specific subtexture of the glyph, 
* Outputs its size and the amount it advances the cursor.
* If either output parameter is NULL, that parameter is ignored.
*/
SubTexture FontGetChar(BitmapFont* font, float fontSize, char ch, vec2* size, float* advance);